### ISSUE TITLE
Trying to login throws error

### ISSUE THREAD

**Issue by SyndiShanX** [summer/mojang#1]
I get an error whenever I try to login

**Login.py:**
```
from mojang import MojangUser

user = MojangUser("Username", "Password")

```

**Error:**
```
Traceback (most recent call last):
  File "Login.py", line 3, in <module>
    user = MojangUser("Username", "Password")
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\user.py", line 80, in __init__
    self._populate_members()
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\utils.py", line 95, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\user.py", line 97, in _populate_members
    self.profile = Profile(self.session)
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\profile.py", line 55, in __init__
    self.update_cache()
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\profile.py", line 85, in update_cache
    self._update_name_data()
  File "C:\Users\syndishanx\AppData\Local\Programs\Python\Python38\lib\site-packages\mojang\profile.py", line 59, in _update_name_data
    self.name_changed_at = data["changedAt"]
KeyError: 'changedAt'
```

**Comment by SyndiShanX** [comment]
I fixed it by adding a check in profile.py to see if the name has ever changed

**Line 34:**
```
    def _update_name_data(self) -> None:
        data = self._session._request("get", f"https://api.mojang.com/user/profile/{self.id}/name").json()
        if 'changedAt' in data:
            self.name_changed_at = data["changedAt"]
            self.is_name_change_allowed = data["nameChangeAllowed"]
        else:
            print("Name has never Changed")
```

**Comment by summer** [comment]
Thanks, should be fixed. The variables will be set to _None_ if they don't exist.
